### PR TITLE
Enable hiera for ssh::server::match_block; fix hostkeys type errors

### PR DESCRIPTION
**Pull request by esalberg**
Allow setting ssh::server::match_block from hiera and update README.markdown; add type to absent hostkeys resources to fix upgrade errors

### CODE REVIEW

**Comment by esalberg** [comment]
I normally would try to separate these out, but I wasn't able to get the updated version of puppet-ssh to run for my nodes until I added the type parameter for the hostkeys.

**Comment by stephen-kainos** [comment]
any chance of getting this merged?

**Comment by esalberg** [comment]
This is my fault - I completely forgot.  I'll get it updated today.

**Comment by stephen-kainos** [comment]
Thanks :)

**Comment by esalberg** [comment]
Actually, my mistake - I thought this was for a different PR that I needed to update before it could be merged.  Sorry about that - the maintainer(s) will need to take the next step here.

**Pull request merged**
