### PR TITLE
bump puppet/systemd to < 5.0.0

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
It looks like the centos 7 acceptance tests need to be kicked.

**Comment by jhoblitt** [comment]
I've touch'd the commit to force gha to re-run.

**Comment by jhoblitt** [comment]
@saz It looks like beaker auto generated centos 7 image is broken. I've reproduced the same failure locally in other modulesync'd repos but I don't know what is wrong.

**Comment by saz** [comment]
Thanks @jhoblitt!

**Comment by jhoblitt** [comment]
Kudos to @bastelfreak for the gha fix.

**Pull request merged**
