### PR TITLE
Add deep merge to server_instances lookup_options

### PR DESCRIPTION
**Pull request by C24-AK**
Small Adjustments to lookup_options

### CODE REVIEW

**Comment by C24-AK** [comment]
Build Pipeline Error is not related to this PR.

**Comment by C24-AK** [comment]
Hello @saz ,
could you look over the Pipeline Errors?

**Comment by saz** [comment]
@C24-AK Please rebase against master.

**Comment by saz** [comment]
There are a lot of things in the PR, which shouldn't be a part of it. I'll pick what I need and create a new PR.

**Pull request closed without merging**
