### PR TITLE
bump upper limit of dependency concat

### PR DESCRIPTION
**Pull request by toepi**

### CODE REVIEW

**Comment by joekohlsdorf** [comment]
Why would you want to do that?

**Comment by toepi** [comment]
To be able to use newer version of concat and this module in same codebase.

**Comment by joekohlsdorf** [comment]
The latest version of concat is 4.1.1, therefore it doesn't make sense to allow version 5.
Maybe you aren't using the devel branch in your tests, the change to allow version 4 hasn't yet been merged to master.

**Comment by saz** [comment]
Master should be working without problems with concat < 5.0.0


And as I've got more time now, I'll add a new release soon.

**Comment by toepi** [comment]
sry, you are right current master has < 5 and should work with 4.1.1 - I've check forge and see version is too low and needs a bump, but than have not see is already done in master.

**Pull request closed without merging**
