### PR TITLE
Removed overrides with hiera_hash

### PR DESCRIPTION
**Pull request by gerapeldoorn**
for options and match_block.

With the current version, I cannot do a deep merge as configured with Hiera:

```
lookup_options:
  ssh::server::options:
    merge:
      strategy: deep
      knockout_prefix: --
```

Thanks!

### CODE REVIEW

**Comment by gerapeldoorn** [comment]
Failed check seems to have no relation with my code. IDK what happened there.

**Comment by joekohlsdorf** [comment]
This is not the right way to fix it, deep_merge should be done in the module itself with `lookup`.

**Comment by gerapeldoorn** [comment]
@joekohlsdorf Thanks for looking at it, I'm not aware of any best practice regarding this.

So if I understand correctly just changing these lines would be the better option?

$hiera_options = lookup("${module_name}::server::options", Optional[Hash], deep, undef)
￼$hiera_match_block = lookup("${module_name}::server::match_block", Optional[Hash], deep, undef)

Thanks,
Ger

**Comment by joekohlsdorf** [comment]
Move the `deep` to the default argument of the `lookup()` function and leave the merge behaviour argument unconfigured. That will allow the user to change the merge behaviour from Hiera data:
https://puppet.com/docs/puppet/5.0/hiera_use_function.html
https://puppet.com/docs/puppet/5.0/hiera_merging.html#configuring-merge-behavior-in-hiera-data

**Comment by gerapeldoorn** [comment]
@saz not really, you can add this lookup_options-key in any Hiera location.

**Pull request closed without merging**
